modLoader="javafml"
loaderVersion="[1,)"
license = "${project_license}"

issueTrackerURL = "${issues_tracker_url}"
showAsResourcePack = false

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
${mod_description}
In loving memory of §d${ng_name}§f.
'''
authors = "${mod_author}"
displayURL= "${website_url}"

logoFile = "assets/${mod_id}/icon_64.png"
credits = "Everyone who contributed on Crowdin and GitHub."
updateJSONURL = "${source_url}/raw/refs/heads/${minecraft_version}/.github/neoforge-update.json"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange= "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
